permalink: /:categories/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "blog/", "notebooks/"]
auto: false
pygments: true


markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc

