permalink: /:categories/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true


markdown: redcarpet
rdiscount:
  extensions:
    - smart
    - generate_toc

