permalink: /:categories/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: false
pygments: true


markdown: maruku
rdiscount:
  extensions:
    - smart
    - generate_toc

